controller_manager:
  ros__parameters:
    #update_rate: 500  # Hz
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    # forward_velocity_controller:
    #   type: forward_command_controller/ForwardCommandController

    position_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

forward_position_controller:
  ros__parameters:
    joints:
      - FL_HAA
      # - FL_HFE
      # - FL_KFE
      # - FR_HAA
      # - FR_HFE
      # - FR_KFE
      # - HL_HAA
      # - HL_HFE
      # - HL_KFE
      # - HR_HAA
      # - HR_HFE
      # - HR_KFE
    interface_name: position
