robot:
    interface: enp3s0
    joint_modules:
        motor_numbers: [2]
        motor_constants: 0.025
        gear_ratios: 9.
        max_currents: 12.
        reverse_polarities: [true]
        lower_joint_limits: [-2.8]
        upper_joint_limits: [2.8]
        max_joint_velocities: 80.
        safety_damping: 0.2
    imu:
        rotate_vector: [1, 2, 3]
        orientation_vector: [1, 2, 3, 4]
joint_calibrator:
    # Can be either POS, NEG, ALT or AUTO
    search_methods: [POS]
    # position_offsets: [
    #    0.179, 0.497, 0.360,
    #   -0.594, 0.219, 0.602,
    #    0.543, 0.539, 0.436,
    #   -0.241, 0.440, 0.210
    # ]
    position_offsets: [
        0.0
        #0.1645,    0.5631,   0.01276,   -0.3575,  -0.01217,    0.3326, -0.008315,    0.8797,      0.55,    0.2471,   -0.2181,   0.07107
        #0.6678,     0.544,   0.03107,   0.01431, 0.0001236,    0.3054,   -0.1134,   0.07692,    0.6065,   -0.1032,   -0.1326,   0.07379
        #-0.04069,   0.5635, 0.003173,  -0.1129, -0.04115,  -0.2976,  -0.1007,  -0.5435,   0.6642,  -0.2579,  -0.1517,  -0.5887
    ]
    calib_order: [0]
    calib_pos: [-2.4]
    Kp: 5.
    Kd: 0.05
    T: 1.
    dt: 0.001
