robot:
    interface: enp3s0
    joint_modules:
        motor_numbers: [4]
        motor_constants: 0.025
        gear_ratios: 9.
        max_currents: 12.
        reverse_polarities: [
            false
        ]
        lower_joint_limits: [
             -2.8,
        ]
        upper_joint_limits: [
             2.8,
        ]
        max_joint_velocities: 80.
        safety_damping: 0.2
    imu:
        rotate_vector: [1, 2, 3]
        orientation_vector: [1, 2, 3, 4]
joint_calibrator:
    # Can be either POS, NEG, ALT or AUTO
    search_methods: [
       POS
    ]
    position_offsets: [
        0.0
    ]
    calib_order: [1]
    calib_pos: [
       -2.4,
    ]
    Kp: 5.
    Kd: 0.05 
    T: 1.
    dt: 0.001
